Оптимизаций кода + изменение документации
TheCrazyWolf/Api-Client-for-samgk.ru pull request #28
Opened 2024-12-20 22:37 UTC by Rysik5318

## Описание
- Измение документации
- Оптимизация кода
- Редактирование summary в ClientSamgkOutputResponse

**Прочая информация**:

<br />

## Типы изменений
- [x] Исправление ошибки (не нарушающее нормальную работу изменение, устраняющее проблему)
- [x] Новая функция (не нарушающее функциональность изменение, добавляющее функциональность)
- [x] Сильное изменение (исправление или функция, которая приведет к изменению существующей функциональности)
- [x] Документация
<br />

## Контрольный список для принятия pull request
- [x] Я проверил, что проект может быть скомпилирован
- [x] Я протестировал свои изменения, и они сработали так, как ожидалось

### Другое
- [x] Требуется дополнительное тестирование

2024-12-21 06:40 UTC, TheCrazyWolf commented
@maksim789456 глянь что здесь произошло

2024-12-21 09:18 UTC, maksim789456 requested changes
В целом все хорошо, но есть моменты которые надо исправить:

- Кое где кривая кодировка коментариев, win-1251 или подобное. Все файлы в проекте в UTF-8
- Оставленный закоментированный старый код. Не стоит так делать т.к. git хранит историю изменений, так что его надо убрать
- В многих местах неправильное наименование методов, полей. Придерживайся гайдлайнов от [Microsoft](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members)
- Убирание модификаторов доступа. Мы все прерасно помним что сущности без модификатора доступа будут как private, но не надо это доводить до крайности и убирать намерено модификаторы. Код читается более удобнее если модификатор написан явно
- Неуместные коментарии по коду. Не надо превращять кодовую базу в свои личные заметки. Так же если ты хочешь что-то еще доделать, то создавай PR как draft

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Common/CommonSamgkController.cs
> +    //protected async Task SendRequest(string url, Method method = Method.Get, object? body = null) // ����� �� ������������
Коментарий написан в win-1251 хотя все файлы в проекте в UTF-8

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Common/CommonSamgkController.cs
> +        // ������� ���
Опять win-1251

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Controllers/ScheduleController.cs
> +    IEnumerable<object> getCacheByType(ScheduleSearchType type) => type switch
Не хватает модификатора доступа, нейминг желательно исправить до `GetScheduleUrl`

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Controllers/ScheduleController.cs
> +    string getIdByType(ScheduleSearchType type, object item) => type switch
Такая же история

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Controllers/ScheduleController.cs
> +        //return type switch // Хотя можно и так, но я люблю изобретать велосипед
Вместо коментирования старого кода, заменяй его полностью
В истории git'а он все равно останется

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Interfaces/Client/ICabController.cs
> +    /// Получить список кабинетов.
Точки в данном случае абслолютно тут не к чему

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgk/Utils/HeadersUtils.cs
> +    //private static ICollection<KeyValuePair<string,string>> GetHeaders() // ����� ��� ��� ������ ��������� �������? (�������) P.s. � �����, ����� �������� dickPick
Опять какая то беда с кодировкой

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgkOutputResponse/Implementation/Cabs/ResultOutCab.cs
> +    string getCampus(string fullAdress)
Очень странные изменения, к чему было убирать модификатор доступа и кривить нейминг 0_o

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgkOutputResponse/Interfaces/Groups/IResultOutGroup.cs
> +    /// ID куратора группы, которые не работает и не совпадает с реальной жизнью. // Правда
Коментарий не в тему

2024-12-21 09:18 UTC, maksim789456 commented on ClientSamgkOutputResponse/Implementation/Identity/ResultOutIdentity.cs
> +    string getShortName() // ���������
Кодировка, нарушение нейминга, отсуствия модификатора доступа

2024-12-21 12:49 UTC, TheCrazyWolf requested changes
Доработать нейминг, кодировку

2024-12-21 19:51 UTC, Rysik5318 commented
Вроде бы всё

2024-12-23 02:40 UTC, maksim789456 approved these changes
Все окей кроме нескольких моментов, но их сам поправлю

2024-12-23 16:38 UTC, merged